# PostgreSQL configuration (Supabase default, override with env vars)
#spring.datasource.url=${SUPABASE_DB_URL}
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.username=${SUPABASE_DB_USER}
#spring.datasource.password=${SUPABASE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.kdmxcvlenegvqxpgbaqg
spring.datasource.password=U7thxqU8NDlVuRKy


spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.datasource.hikari.data-source-properties.preparedStatementCacheQueries=0
spring.datasource.hikari.data-source-properties.preparedStatementCacheSizeMiB=0
# JPA configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server configuration
server.port=${PORT:8080}

# Disable SQL script initialization
spring.sql.init.mode=never

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
